### PR TITLE
It works?

### PR DESCRIPTION
**Pull request by master801**
Cleaned up the classes a little bit (not much was done.)
Made it work properly (not really sure since I don't know what the program is supposed to do.)

Added .gitignore files - This makes ensures that some files won't be uploaded to Git (classes, project-specific files, etc...)

Feel free to ask any questions regarding this pull request, whether it's about why I did something a specific way or something else.

### CODE REVIEW

**Comment by SachinBarpanda** [comment]
Thanks, bro! That was great actually and it worked actually can't believe it did.
But one thing, the previous program was right!
If not then can you tell me where It did wrong
I think the String parameters when passed through a boolean,  then it was not returning anything.
But the tutorial that I was watching did the same thing and it did work for him.
So, if you can specify me where was the programming error was then it would be great
And besides that, where do we use 'final' keyword or why do we use it, I mean you store the songs in an array first then How did you manage to use linked list after that in it. Is it because of the FINAL keyword you used.

**Comment by master801** [comment]
Could you explain what you mean by "right?"

I think your main issue was [this](https://github.com/SachinBarpanda/Playlist-songs-LinkedList/blob/SachinBarpanda-patch-1/Linked%20List/src/com/Sachin/Main.java#L31) specific part. It looks like you [previously set the variable to a value,](https://github.com/SachinBarpanda/Playlist-songs-LinkedList/blob/SachinBarpanda-patch-1/Linked%20List/src/com/Sachin/Main.java#L15) [added it to a list](https://github.com/SachinBarpanda/Playlist-songs-LinkedList/blob/SachinBarpanda-patch-1/Linked%20List/src/com/Sachin/Main.java#L29), then [set the same variable to another value](https://github.com/SachinBarpanda/Playlist-songs-LinkedList/blob/SachinBarpanda-patch-1/Linked%20List/src/com/Sachin/Main.java#L31). I'm not entirely sure, but the first variable that was added to the list will be "overwritten" with the new value. This is how Python handled it, so I'm not entirely sure as to how Java would handle it, but I think it's the same concept.


The final modifier will not allow the variable to be set, only read. This should be only used on method parameters and _some_ class fields. Personally, I only use the final modifier as a safe practice to do, rather than it being functional other than it being used properly (for variables that will never be changed.)

The reason why it should be used on method parameters is simply because method parameters should **not** be set within a method. So if your method has a parameter, you should not be setting it to a value. It can be done, but it's a poor practice to do and not recommended to do at all since it will cause issues and in general looks pretty bad.

Poor practice:
``` java
public void doSomething(String name) {
System.out.println(name);//name will be something
name = "New name";//name will now be set to "New name" - Poor practice
System.out.println(name);
}
```

Better:
``` java
public void doSomething(final String name) {
String ourName = name;//Use a local variable instead of directly setting the method parameter's value

System.out.println(ourName);
ourName = "New name";
System.out.println();
}
```


Some class fields should be final only if you're never going to set them again. A simple one-use-only case. However, if using the final modifier on class fields, the value must be set within the class' constructor or set to a default variable.

Example:
``` java
public AClass {

private final String name;
private final List<Object> alwaysHere = new ArrayList<>();//Set to a default variable

public AClass(final String name) {
this.name = name; // The "this" modifier signifies that we're using this class' field, not the method parameter
}

}
```


The albums are stored as an array since they're never going to be changed, only read from. You're bound to create more bugs if dynamically creating objects. However, if the albums were dynamically created, I would've used an array anyway, but would've done it a little differently.

The songs were added using this [method](https://github.com/master801/Playlist-songs-LinkedList/blob/5f4389c747881069a6537c5aaed1fa5cf5add956/Linked%20List/src/com/Sachin/Main.java#L13). In the method, we're checking if the song is null (it'll never be null, but I'm checking it anyway) or if the album already has the song. If these statements are true, then we prematurely stop the method from adding the song to album.

That kind of practice is usually only done in builder type classes, but it can be applied to any class that needs it. I only did it since the albums are created in an array. Another way it could've been done is to add a "songs" array in the constructor and then just set it in the class. There's no real way to "correctly" do this.

``` java
public class Something {

private final Objects[] objects;

public Something(final Object[] objects) {
this.objects = objects;
}

}
```

If you need a more thorough explanation, I'd be happy to explain.

**Comment by SachinBarpanda** [comment]
Oh, now I am understanding a bit about the Final but can you please tell me this:-

I think the String parameters when passed through a boolean, then it was not returning anything.
But the tutorial that I was watching did the same thing and it did work for him.
So, if you can specify me where was the programming error was then it would be great

` public boolean addSongToPlaylist(String title, LinkedList <Song> playlist) {      
        

       Song checkedSongs = findSong(title);
        if (checkedSongs != null) {
            playlist.add(checkedSongs);
            return true;
        }
        System.out.println("The song " + title + " is not available");
        return false;
    }`

**Comment by SachinBarpanda** [comment]
And yeah I am unable to write code in the space saying insert code.HAHA

**Comment by master801** [comment]
Alright, I think I found the error.

One of your variables was incorrectly used. [Here](https://github.com/SachinBarpanda/Playlist-songs-LinkedList/blob/SachinBarpanda-patch-1/Linked%20List/src/com/Sachin/Album.java#L19) you should be using the variable "title" (since it's the name of the song), but you (mis-typed?) "name" (which is the name of the album.)

I changed it to the correct value ("title") and got the expected results.

I guess I should've just debugged it first before changing things up lol

**Comment by SachinBarpanda** [comment]
Oh god, shit man!
Yeah, you're right, anyway Thanks for solving and helping me along the process. Heartfully, appreciate your support! Hope to see you soon.
And One more thing how would debugging would have helped you to find the errors.

**Comment by SachinBarpanda** [comment]
And about that, no it didn't work man. I think it's some problem with the JDK or something else. I don't know but when you hover the mouse on the method name it shows return values not used in the ........

So I guess I have to go with you ^^

**Pull request closed without merging**
